### ISSUE TITLE
classification issue

### ISSUE THREAD

**Issue by arssoy** [kroczi/genetic-image-classification#13]
Hi,
thank you for providing us this code, I followed all the steps mentioned above. The process of creating binary classifiers is well done. Unfortunately I have an issue with the classification process while executing both of the command  One versus one or All pairs filter tree. This is the result:

![error](https://user-images.githubusercontent.com/34400846/38381459-bdfa9194-38fe-11e8-987c-be674ce118d8.PNG)

Any help will be appreciated. 
Thank you

**Comment by kroczi** [comment]
Hi @arssoy,

It is niece to hear that you are interested in our project. It seems that there is some problem with the binary classifiers that you provide to the multiclass analysis. Could you present a few sample lines from the classifiers file?
Also, which version of DEAP library are you using? We recommend trying using version 1.0.1 or 1.0.2. Also please make sure that you introduced the slight modification to the library function `generate`, as described in the README.

**Comment by arssoy** [comment]
hi @kroczi ,
we are using deap 1.2.2 and we did the proposed modification in the `generate`  function as described in the README file.
We obtained the `info.log` file that contains the binary classifiers. 
But we think that the format of the binary classifiers that is used as an input to the multiclass analysis is wrong. We would like that you check it with us and here is few sample lines from the classifier file:

`KTH-TIPS2/;0;1;1469.3539662361145;{'avg': 18.31, 'std': 3.390265476330725, 'min': 9.0, 'max': 20.0, 'learn_rate': 1.0};sub(bins3(HoG(IN0, Shape(0), Position(180, 129), Size(132, 25)), Index(5)), div3(distance3(HoG(IN0, Shape(0), Position(187, 140), Size(49, 175)), HoG(IN0, Shape(0), Position(175, 165), Size(194, 158))), distance3(HoG(IN0, Shape(0), Position(123, 183), Size(51, 137)), HoG(IN0, Shape(1), Position(163, 124), Size(36, 32)))));0.8;0.8;0.8`



>

**Comment by kroczi** [comment]
Oh I see, as the classifier file you do not need to provide the whole content of the `info.log` file, but only the string representation of classifiers - the fourth to last column of the `info.log`. 
Alternatively, You can modify the last line of the [`evaluate_classifier`](https://github.com/kroczi/genetic-image-classification/blob/2e1a8f3aaee288af3e8988f3d34d2ad0d9f16315/binary/binary_classifier_evaluator.py#L87) function to log only the `str(hof[0])` and then pass the whole `info.log` file as the classifier file.

**Comment by kroczi** [comment]
Did you manage to solve the problem? Can we close the issue?
